= *Cahier des charges utilisateur*

[cols="1,1", options="header"]
|===
| Version | Date

| V1 | 12 mai 2023 
|===


*Équipe :* 1A1 
[cols="1,1,1,1"]
|===
|Pablo MARQUET | Chris ACHE | Nelson FRANCE | Maxime PEYBERNES
|===

=== DailyBank

= Sommaire


* <<PresProj,Présentation du projet>>
* <<Obj,Objectifs>>
* <<IdUtil>>
* <<AnaExis>>
* <<AnaBes>>
* <<Liv>>
* <<AnaCont>>

[[PresProj]]
= Présentation du projet 

Ce projet a pour but de réaliser une application Java qui puisse gérer les comptes des clients d’une banque. Il est cadré par 2 SAE distinctes : la S2.05 (gestion de projet) et la S2.01 (développement d’application). Dans ce cadre, nous avons à réaliser, au-delà du développement et des documents qui y sont liés, des rendus liés à la gestion de notre temps (gantt), des tâches à réaliser (issues sur GitHub) et sur le projet en lui-même (cahier des charges). 

[[Obj]]
= Objectifs

BLAH

[[IdUtil]]
= Indetification des utilisateurs

BLAH

[[AnaExis]]
= Analyse de l'existant

BLAH

[[AnaBes]]
= Analyse du besoin

BLAH

[[Liv]]
= Livrables

BLAH

[[AnaCont]]
= Analyse des contraintes

BLAH
